# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # Clang-format for C++ formatting
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6  # Use the latest stable version
    hooks:
      - id: clang-format
        types_or: [c++, c]
        args: ['-i']  # In-place formatting

  # Clang-tidy for C++ static analysis
  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: ./tools/run-clang-tidy.sh
        language: system
        types_or: [c++, c]
        args: ['--build-dir', 'build/Debug', '--jobs', '4']
        pass_filenames: false
        always_run: true

  # General file fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: '^.*\.(md|rst)$'
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: check-merge-conflict
      - id: check-case-conflict

  # Python code formatting (for Python bindings and tests)
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        files: '^(tests/python/|bindings/).*\.py$'

  # Python imports sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: '^(tests/python/|bindings/).*\.py$'

  # Python linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=120', '--extend-ignore=E203,W503']
        files: '^(tests/python/|bindings/).*\.py$'

# Configuration for specific tools
default_language_version:
  python: python3

# Files to exclude from all hooks
exclude: |
  (?x)^(
    build/.*|
    build-.*/.*|
    cmake-build-.*/.*|
    \.git/.*|
    __pycache__/.*|
    .*\.egg-info/.*|
    dist/.*|
    docs/_build/.*
  )$
